#! /bin/sh
### BEGIN INIT INFO
# Provides:             pewss-server
# Required-Start:       $local_fs $network redis-server mongodb
# Required-Stop:        $local_fs $network redis-server mongodb
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Pewss Server
# Description:          Pewss Server
### END INIT INFO

NAME='pewss'

export NODE_ENV='production'

[ -r /etc/default/pewss ] && . /etc/default/pewss

: ${APP_DIR:='/var/www/Pewss'}
: ${USER:='nobody'}
: ${NODE:='/usr/bin/node'}
: ${DIE_TIME:=10}
: ${START_TIME:=2}

APP="$APP_DIR/Build/Server/Entry.js"
PID_FILE="/var/run/pewss.pid"

. /lib/lsb/init-functions

is_start () {
  if [ -f $PID_FILE ]; then
    return 0
  else
    return 1
  fi
}

do_start () {
  start-stop-daemon -S -d $APP_DIR -c $USER -m -p $PID_FILE -b -x $NODE -- $APP
  return $?
}

do_stop () {
  start-stop-daemon -K -c $USER -p $PID_FILE
  rm $PID_FILE
  return $?
}

start () {
  log_daemon_msg "Starting $NAME"
  if is_start;  then
    log_progress_msg "Pewss already running."
    log_end_msg 0
    exit 0
  fi

  if do_start; then
    sleep $START_TIME
    if is_start; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
  else
    log_end_msg 1
  fi
}

stop () {
  log_daemon_msg "Stopping $NAME"
  if is_start; then
    do_stop
    log_end_msg $?
  else
    log_progress_msg "Pewss not running."
    log_end_msg 0
  fi
}

status () {
  log_daemon_msg "Checking status of $NAME"
  if is_start; then
    log_progress_msg "Pewss is running."
    log_end_msg 0
  else
    log_progress_msg "Pewss is not running."
    log_end_msg 1
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
