#! /bin/sh
### BEGIN INIT INFO
# Provides:             pewss-server
# Required-Start:       $local_fs $network redis-server mongodb
# Required-Stop:        $local_fs $network redis-server mongodb
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Pewss Server
# Description:          Pewss Server
### END INIT INFO

# ln -s ./pewss /etc/init.d/pewss
# sudo update-rc.d pewss defaults
# sudo update-rc.d pewss enable

NAME="pewss"
export NODE_ENV="production"
export PATH=/home/tsmh/.nvm/versions/node/v8.4.0/bin:$PATH

[ -r /etc/default/pewss ] && . /etc/default/pewss

: ${APPPATH:="/pewss"}
NMODULES="$APPPATH/node_modules"
FOREVER="$NMODULES/forever/bin/forever"
APP="$APPPATH/Build/Server/Entry.js"

: ${DIETIME:=10}
: ${STARTTIME:=2}

is_start () {
  $FOREVER list 2>/dev/null | grep $APP 2>&1 >/dev/null
  return $?
}

do_start () {
  $FOREVER start $APP 2>&1 >/dev/null
  return $?
}

do_stop () {
  $FOREVER stop $APP 2>&1 >/dev/null
  return $?
}

. /lib/lsb/init-functions

start () {
  log_daemon_msg "Starting $NAME"
  if is_start;  then
    log_progress_msg "Pewss already running."
    log_end_msg 0
    exit 0
  fi

  if do_start; then
    sleep $STARTTIME
    if is_start; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
  else
    log_end_msg 1
  fi
}

stop () {
  log_daemon_msg "Stopping $NAME"
  if is_start; then
    do_stop
    log_end_msg $?
  else
    log_progress_msg "Pewss not running."
    log_end_msg 0
  fi
}

status () {
  log_daemon_msg "Checking status of $NAME"
  if is_start; then
    log_progress_msg "Pewss is running."
    log_end_msg 0
  else
    log_progress_msg "Pewss is not running."
    log_end_msg 1
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|force-reload)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
    exit 1
    ;;
esac

exit 0
